site_name: Taller de computació paral·lela amb Raspberry Pi
site_url: https://example.com/
docs_dir: "md"
site_dir: "docs"
nav:
    - Configuració: 1._ClusterPi_Muntatge_i_configuració_del_clúster.md
    - Programació: 2._ClusterPI_Programació_paral·lela.md

theme: 
  name: material
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


